import Foundation
import FirebaseFirestore

// MARK: - User

enum UserRole: String, Codable {
    case student
    case professor
}

struct AppUser: Codable, Identifiable {
    @DocumentID var id: String?
    var uid: String
    var email: String
    var displayName: String
    var role: UserRole
    var enrolledCourses: [String]
    var expoPushToken: String?

    var isProfessor: Bool { role == .professor }
}

// MARK: - Course

struct Course: Codable, Identifiable {
    @DocumentID var id: String?
    var courseCode: String
    var title: String
    var description: String
    var professorId: String
    var professorName: String
    var term: String
    var enrollmentOpen: Bool
    var color: String
    var meetingTimes: String?
    var location: String?
}

// MARK: - Assignment

enum AssignmentType: String, Codable {
    case reading, essay, homework, quiz, exam, project, presentation, response, custom
}

struct Assignment: Codable, Identifiable {
    @DocumentID var id: String?
    var courseId: String
    var title: String
    var description: String
    var dueDate: Timestamp
    var type: AssignmentType
    var totalPoints: Int
    var createdBy: String
    var isCustom: Bool
    var estimatedMinutes: Int?

    var dueDateFormatted: String {
        let df = DateFormatter()
        df.dateStyle = .medium
        return df.string(from: dueDate.dateValue())
    }

    var daysUntilDue: Int {
        Calendar.current.dateComponents([.day], from: Date(), to: dueDate.dateValue()).day ?? 0
    }
}

// MARK: - Task

struct AssignmentTask: Codable, Identifiable {
    @DocumentID var id: String?
    var assignmentId: String
    var courseId: String
    var title: String
    var description: String?
    var dueDate: Timestamp
    var order: Int
    var estimatedMinutes: Int
    var isAutoGenerated: Bool
}

// MARK: - Task Progress

struct TaskProgress: Codable, Identifiable {
    @DocumentID var id: String?
    var taskId: String
    var assignmentId: String
    var courseId: String
    var completed: Bool
    var completedAt: Timestamp?
    var notes: String?
}
